title: HRI Development
email: weijingjaylin[at]gmail.com
description: A  web to help me understanding HRI development.
baseurl: './hri-development'
url: ''
twitter_username: dotku
github_username: dotku
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-admin
