avatar: assets/images/avatar.jpg
title: HRI Development
email: weijingjaylin[at]gmail.com
description: A  web to help me understanding HRI development.
baseurl: 'hri-development'
url: 'https://dotku.github.io'
twitter_username: dotku
github_username: dotku
markdown: kramdown
theme: jekyll-text-theme
plugins:
  - jekyll-feed
  - jekyll-admin
destination: 'docs'
theme: jekyll-theme-prologue
